name: zhihu
description: Flutter zhihu app.
publish_to: 'none'
version: 1.0.8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  intl: ^0.17.0
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  flutter_widget_from_html_core: ^0.8.0
  cached_network_image: ^3.1.0
  chewie: ^1.2.2
  url_launcher: ^6.0.12
  webview_flutter: ^2.1.1
  webview_cookie_manager: ^2.0.6
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
