name: zhihu
description: Flutter zhihu app.
publish_to: 'none'
version: 1.0.8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.17.0
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  flutter_widget_from_html_core: ^0.8.5+3
  cached_network_image: ^3.2.1
  chewie: ^1.3.4
  url_launcher: ^6.1.4
  webview_flutter: ^3.0.4
  webview_cookie_manager: ^2.0.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
