name: zhihu
description: Flutter zhihu app.
publish_to: 'none'
version: 1.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  intl:
  dio:
  dio_http2_adapter:
  flutter_widget_from_html_core:
  cached_network_image:
  chewie:
  url_launcher:
  flutter_webview_plugin:
  webview_cookie_manager:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
